//! GitHub Actions workflow generation.
//!
//! Generates workflow YAML files for Cortex CI/CD automation.

use serde::{Deserialize, Serialize};

/// Workflow configuration options.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowConfig {
    /// Workflow name.
    pub name: String,
    /// Enable PR review automation.
    pub pr_review: bool,
    /// Enable issue automation.
    pub issue_automation: bool,
}

impl Default for WorkflowConfig {
    fn default() -> Self {
        Self {
            name: "Cortex".to_string(),
            pr_review: true,
            issue_automation: true,
        }
    }
}

/// Generate a GitHub Actions workflow YAML.
pub fn generate_workflow(config: &WorkflowConfig) -> String {
    let mut triggers = Vec::new();

    if config.issue_automation {
        triggers.push("issue_comment");
    }
    if config.pr_review {
        triggers.push("pull_request");
        triggers.push("pull_request_review");
    }

    // Build the triggers YAML
    let triggers_yaml = if triggers.is_empty() {
        "  workflow_dispatch:".to_string()
    } else {
        let mut yaml = String::new();
        for trigger in &triggers {
            match *trigger {
                "issue_comment" => {
                    yaml.push_str("  issue_comment:\n");
                    yaml.push_str("    types: [created]\n");
                }
                "pull_request" => {
                    yaml.push_str("  pull_request:\n");
                    yaml.push_str("    types: [opened, synchronize, reopened]\n");
                }
                "pull_request_review" => {
                    yaml.push_str("  pull_request_review:\n");
                    yaml.push_str("    types: [submitted]\n");
                }
                _ => {}
            }
        }
        yaml.push_str("  workflow_dispatch:");
        yaml
    };

    format!(
        r#"# Cortex CI/CD Automation
# Generated by: cortex github install
# Documentation: https://docs.cortex.foundation/github

name: {name}

on:
{triggers}

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  cortex:
    runs-on: ubuntu-latest
    # Only run on comments that mention cortex
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && 
       (contains(github.event.comment.body, '@cortex') || 
        contains(github.event.comment.body, '/cortex')))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Cortex CLI
        run: |
          curl -fsSL https://software.cortex.foundation/install.sh | sh
          echo "$HOME/.cortex/bin" >> $GITHUB_PATH
      
      - name: Run Cortex Agent
        env:
          CORTEX_API_KEY: ${{{{ secrets.CORTEX_API_KEY }}}}
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          cortex github run \
            --event "${{{{ github.event_name }}}}" \
            --token "${{{{ secrets.GITHUB_TOKEN }}}}" \
            --repository "${{{{ github.repository }}}}"
"#,
        name = config.name,
        triggers = triggers_yaml,
    )
}

/// Generate a minimal workflow for just PR reviews.
pub fn generate_pr_review_workflow(name: &str) -> String {
    format!(
        r#"# Cortex PR Review Automation
# Generated by: cortex github install --pr-only

name: {name}

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Cortex
        run: |
          curl -fsSL https://software.cortex.foundation/install.sh | sh
          echo "$HOME/.cortex/bin" >> $GITHUB_PATH
      
      - name: Review PR
        env:
          CORTEX_API_KEY: ${{{{ secrets.CORTEX_API_KEY }}}}
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          cortex github run \
            --event "pull_request" \
            --token "${{{{ secrets.GITHUB_TOKEN }}}}" \
            --repository "${{{{ github.repository }}}}"
"#,
        name = name,
    )
}

/// Generate a workflow for issue triage.
pub fn generate_issue_triage_workflow(name: &str) -> String {
    format!(
        r#"# Cortex Issue Triage Automation
# Generated by: cortex github install --issues-only

name: {name}

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' ||
      (github.event_name == 'issue_comment' && 
       (contains(github.event.comment.body, '@cortex') || 
        contains(github.event.comment.body, '/cortex')))
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Cortex
        run: |
          curl -fsSL https://software.cortex.foundation/install.sh | sh
          echo "$HOME/.cortex/bin" >> $GITHUB_PATH
      
      - name: Process Issue
        env:
          CORTEX_API_KEY: ${{{{ secrets.CORTEX_API_KEY }}}}
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          cortex github run \
            --event "${{{{ github.event_name }}}}" \
            --token "${{{{ secrets.GITHUB_TOKEN }}}}" \
            --repository "${{{{ github.repository }}}}"
"#,
        name = name,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_workflow_default() {
        let config = WorkflowConfig::default();
        let workflow = generate_workflow(&config);

        assert!(workflow.contains("name: Cortex"));
        assert!(workflow.contains("issue_comment:"));
        assert!(workflow.contains("pull_request:"));
        // Check for API key environment variable
        assert!(
            workflow.contains("API_KEY") || workflow.contains("CORTEX_API_KEY"),
            "Should contain API key env var"
        );
    }

    #[test]
    fn test_generate_workflow_pr_only() {
        let config = WorkflowConfig {
            name: "cortex-pr".to_string(),
            pr_review: true,
            issue_automation: false,
        };
        let workflow = generate_workflow(&config);

        assert!(workflow.contains("name: cortex-pr"));
        assert!(workflow.contains("pull_request:"));
        assert!(!workflow.contains("issue_comment:"));
    }

    #[test]
    fn test_generate_pr_review_workflow() {
        let workflow = generate_pr_review_workflow("pr-review");

        assert!(workflow.contains("name: pr-review"));
        assert!(workflow.contains("pull_request:"));
        assert!(!workflow.contains("issue_comment:"));
    }

    #[test]
    fn test_generate_issue_triage_workflow() {
        let workflow = generate_issue_triage_workflow("issue-triage");

        assert!(workflow.contains("name: issue-triage"));
        assert!(workflow.contains("issues:"));
        assert!(workflow.contains("issue_comment:"));
    }
}
