//! Model preset data definitions.

use super::types::ModelPreset;

/// Available model presets.
pub const MODEL_PRESETS: &[ModelPreset] = &[
    ModelPreset {
        id: "gpt-4o",
        name: "GPT-4o",
        provider: "openai",
        context_window: 128_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        provider: "openai",
        context_window: 128_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "o1",
        name: "o1",
        provider: "openai",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
    },
    ModelPreset {
        id: "o1-mini",
        name: "o1-mini",
        provider: "openai",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: true,
    },
    ModelPreset {
        id: "claude-3-5-sonnet",
        name: "Claude 3.5 Sonnet",
        provider: "anthropic",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "claude-3-opus",
        name: "Claude 3 Opus",
        provider: "anthropic",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    // Google Gemini models
    ModelPreset {
        id: "gemini-2.0-flash-exp",
        name: "Gemini 2.0 Flash (Experimental)",
        provider: "google",
        context_window: 1_048_576,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "gemini-2.0-flash",
        name: "Gemini 2.0 Flash",
        provider: "google",
        context_window: 1_048_576,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "gemini-1.5-pro",
        name: "Gemini 1.5 Pro",
        provider: "google",
        context_window: 2_097_152,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "gemini-1.5-flash",
        name: "Gemini 1.5 Flash",
        provider: "google",
        context_window: 1_048_576,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "gemini-1.5-flash-8b",
        name: "Gemini 1.5 Flash 8B",
        provider: "google",
        context_window: 1_048_576,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    // Mistral AI models
    ModelPreset {
        id: "mistral-large-latest",
        name: "Mistral Large",
        provider: "mistral",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "mistral-medium-latest",
        name: "Mistral Medium",
        provider: "mistral",
        context_window: 32_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "mistral-small-latest",
        name: "Mistral Small",
        provider: "mistral",
        context_window: 32_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "codestral-latest",
        name: "Codestral",
        provider: "mistral",
        context_window: 32_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "open-mixtral-8x22b",
        name: "Mixtral 8x22B",
        provider: "mistral",
        context_window: 64_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "open-mistral-7b",
        name: "Mistral 7B",
        provider: "mistral",
        context_window: 32_000,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "pixtral-large-latest",
        name: "Pixtral Large",
        provider: "mistral",
        context_window: 128_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    // Groq models (ultra-fast inference)
    ModelPreset {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        provider: "groq",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "llama-3.1-70b-versatile",
        name: "Llama 3.1 70B",
        provider: "groq",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B Instant",
        provider: "groq",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "llama3-70b-8192",
        name: "Llama 3 70B",
        provider: "groq",
        context_window: 8_192,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "llama3-8b-8192",
        name: "Llama 3 8B",
        provider: "groq",
        context_window: 8_192,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        provider: "groq",
        context_window: 32_768,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "gemma2-9b-it",
        name: "Gemma 2 9B IT",
        provider: "groq",
        context_window: 8_192,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    // Cerebras models (ultra-fast inference on Wafer-Scale Engine)
    // Cerebras is the fastest inference provider in the industry
    ModelPreset {
        id: "llama3.1-8b",
        name: "Llama 3.1 8B (Cerebras - Ultra Fast)",
        provider: "cerebras",
        context_window: 8_192,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "llama3.1-70b",
        name: "Llama 3.1 70B (Cerebras - Fast)",
        provider: "cerebras",
        context_window: 8_192,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "llama-3.3-70b",
        name: "Llama 3.3 70B (Cerebras - Latest)",
        provider: "cerebras",
        context_window: 8_192,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    // xAI (Grok) models
    ModelPreset {
        id: "grok-2",
        name: "Grok 2",
        provider: "xai",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "grok-2-mini",
        name: "Grok 2 Mini",
        provider: "xai",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "grok-beta",
        name: "Grok Beta",
        provider: "xai",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "grok-vision-beta",
        name: "Grok Vision Beta",
        provider: "xai",
        context_window: 8_000,
        supports_vision: true,
        supports_tools: false,
        supports_reasoning: false,
    },
    // GitHub Copilot models (via Copilot subscription)
    ModelPreset {
        id: "copilot/gpt-4o",
        name: "GPT-4o (via Copilot)",
        provider: "github-copilot",
        context_window: 128_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "copilot/gpt-4o-mini",
        name: "GPT-4o Mini (via Copilot)",
        provider: "github-copilot",
        context_window: 128_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "copilot/claude-3.5-sonnet",
        name: "Claude 3.5 Sonnet (via Copilot)",
        provider: "github-copilot",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "copilot/o1-preview",
        name: "o1-preview (via Copilot)",
        provider: "github-copilot",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
    },
    ModelPreset {
        id: "copilot/o1-mini",
        name: "o1-mini (via Copilot)",
        provider: "github-copilot",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: true,
    },
    // Amazon Bedrock models (via AWS)
    ModelPreset {
        id: "anthropic.claude-3-5-sonnet-20241022-v2:0",
        name: "Claude 3.5 Sonnet v2 (Bedrock)",
        provider: "bedrock",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "anthropic.claude-3-5-haiku-20241022-v1:0",
        name: "Claude 3.5 Haiku (Bedrock)",
        provider: "bedrock",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "anthropic.claude-3-opus-20240229-v1:0",
        name: "Claude 3 Opus (Bedrock)",
        provider: "bedrock",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "anthropic.claude-3-sonnet-20240229-v1:0",
        name: "Claude 3 Sonnet (Bedrock)",
        provider: "bedrock",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "anthropic.claude-3-haiku-20240307-v1:0",
        name: "Claude 3 Haiku (Bedrock)",
        provider: "bedrock",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "meta.llama3-1-70b-instruct-v1:0",
        name: "Llama 3.1 70B (Bedrock)",
        provider: "bedrock",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "meta.llama3-1-8b-instruct-v1:0",
        name: "Llama 3.1 8B (Bedrock)",
        provider: "bedrock",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "amazon.titan-text-premier-v1:0",
        name: "Titan Text Premier (Bedrock)",
        provider: "bedrock",
        context_window: 32_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "amazon.titan-text-express-v1",
        name: "Titan Text Express (Bedrock)",
        provider: "bedrock",
        context_window: 8_000,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "mistral.mistral-large-2407-v1:0",
        name: "Mistral Large (Bedrock)",
        provider: "bedrock",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    // Together AI models
    ModelPreset {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Instruct Turbo",
        provider: "together",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "meta-llama/Llama-3.1-405B-Instruct-Turbo",
        name: "Llama 3.1 405B Instruct Turbo",
        provider: "together",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "mistralai/Mixtral-8x22B-Instruct-v0.1",
        name: "Mixtral 8x22B Instruct v0.1",
        provider: "together",
        context_window: 65_536,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "Qwen/Qwen2.5-72B-Instruct-Turbo",
        name: "Qwen 2.5 72B Instruct Turbo",
        provider: "together",
        context_window: 32_768,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "deepseek-ai/DeepSeek-V3",
        name: "DeepSeek V3",
        provider: "together",
        context_window: 65_536,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "google/gemma-2-27b-it",
        name: "Gemma 2 27B IT",
        provider: "together",
        context_window: 8_192,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    // DeepInfra models (serverless GPU inference)
    ModelPreset {
        id: "deepinfra/meta-llama/Meta-Llama-3.1-405B-Instruct",
        name: "Llama 3.1 405B Instruct (DeepInfra)",
        provider: "deepinfra",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "deepinfra/meta-llama/Meta-Llama-3.1-70B-Instruct",
        name: "Llama 3.1 70B Instruct (DeepInfra)",
        provider: "deepinfra",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "deepinfra/mistralai/Mixtral-8x22B-Instruct-v0.1",
        name: "Mixtral 8x22B Instruct (DeepInfra)",
        provider: "deepinfra",
        context_window: 65_536,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "deepinfra/microsoft/WizardLM-2-8x22B",
        name: "WizardLM 2 8x22B (DeepInfra)",
        provider: "deepinfra",
        context_window: 65_536,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "deepinfra/Qwen/Qwen2.5-72B-Instruct",
        name: "Qwen 2.5 72B Instruct (DeepInfra)",
        provider: "deepinfra",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    // DeepSeek models (direct API access)
    ModelPreset {
        id: "deepseek-chat",
        name: "DeepSeek-V3",
        provider: "deepseek",
        context_window: 64_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "deepseek-coder",
        name: "DeepSeek-Coder",
        provider: "deepseek",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "deepseek-reasoner",
        name: "DeepSeek-R1",
        provider: "deepseek",
        context_window: 64_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: true,
    },
    // Perplexity AI models (search-augmented)
    // Online models (with web search and citations)
    ModelPreset {
        id: "llama-3.1-sonar-small-128k-online",
        name: "Sonar Small Online (8B)",
        provider: "perplexity",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "llama-3.1-sonar-large-128k-online",
        name: "Sonar Large Online (70B)",
        provider: "perplexity",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "llama-3.1-sonar-huge-128k-online",
        name: "Sonar Huge Online (405B)",
        provider: "perplexity",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
    },
    // Chat models (offline, no web search)
    ModelPreset {
        id: "llama-3.1-sonar-small-128k-chat",
        name: "Sonar Small Chat (8B)",
        provider: "perplexity",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "llama-3.1-sonar-large-128k-chat",
        name: "Sonar Large Chat (70B)",
        provider: "perplexity",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
    },
    // Cortex models (200+ models via unified API)
    // These are the most popular models accessible through OpenRouter
    // DEFAULT MODELS
    ModelPreset {
        id: "anthropic/claude-opus-4.5",
        name: "Claude Opus 4.5 (via Cortex) - DEFAULT",
        provider: "cortex",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
    },
    ModelPreset {
        id: "anthropic/claude-haiku-4.5",
        name: "Claude Haiku 4.5 (via Cortex) - DEFAULT",
        provider: "cortex",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    // Other Cortex models
    ModelPreset {
        id: "openai/gpt-4o",
        name: "GPT-4o (via Cortex)",
        provider: "cortex",
        context_window: 128_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "openai/gpt-4o-mini",
        name: "GPT-4o Mini (via Cortex)",
        provider: "cortex",
        context_window: 128_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "anthropic/claude-3.5-sonnet",
        name: "Claude 3.5 Sonnet (via Cortex)",
        provider: "cortex",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "anthropic/claude-3-opus",
        name: "Claude 3 Opus (via Cortex)",
        provider: "cortex",
        context_window: 200_000,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "google/gemini-pro-1.5",
        name: "Gemini 1.5 Pro (via Cortex)",
        provider: "cortex",
        context_window: 2_097_152,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "google/gemini-flash-1.5",
        name: "Gemini 1.5 Flash (via Cortex)",
        provider: "cortex",
        context_window: 1_048_576,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "meta-llama/llama-3.1-405b-instruct",
        name: "Llama 3.1 405B Instruct (via Cortex)",
        provider: "cortex",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "meta-llama/llama-3.1-70b-instruct",
        name: "Llama 3.1 70B Instruct (via Cortex)",
        provider: "cortex",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "mistralai/mistral-large",
        name: "Mistral Large (via Cortex)",
        provider: "cortex",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "mistralai/mixtral-8x22b-instruct",
        name: "Mixtral 8x22B Instruct (via Cortex)",
        provider: "cortex",
        context_window: 65_536,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "deepseek/deepseek-chat",
        name: "DeepSeek Chat (via Cortex)",
        provider: "cortex",
        context_window: 64_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "deepseek/deepseek-r1",
        name: "DeepSeek R1 (via Cortex)",
        provider: "cortex",
        context_window: 64_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: true,
    },
    ModelPreset {
        id: "cohere/command-r-plus",
        name: "Command R+ (via Cortex)",
        provider: "cortex",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    // Cohere models
    ModelPreset {
        id: "command-r-plus",
        name: "Command R+",
        provider: "cohere",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "command-r-plus-08-2024",
        name: "Command R+ (Aug 2024)",
        provider: "cohere",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "command-r",
        name: "Command R",
        provider: "cohere",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "command-r-08-2024",
        name: "Command R (Aug 2024)",
        provider: "cohere",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "command-light",
        name: "Command Light",
        provider: "cohere",
        context_window: 4_096,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
    ModelPreset {
        id: "command-nightly",
        name: "Command Nightly",
        provider: "cohere",
        context_window: 128_000,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
    },
];

/// Get a model preset by ID.
pub fn get_model_preset(id: &str) -> Option<&'static ModelPreset> {
    MODEL_PRESETS.iter().find(|m| m.id == id)
}

/// Get models for a specific provider.
pub fn get_models_for_provider(provider: &str) -> Vec<&'static ModelPreset> {
    MODEL_PRESETS
        .iter()
        .filter(|m| m.provider == provider)
        .collect()
}
